# Generated by Django 4.0.4 on 2022-04-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(default='', verbose_name='Date and time'),
        ),
    ]
